import ReasLib.FunctionalAnalysis.SequenceSpace.RationalTimeOperator.Parametrization.SeedCounterexample

#print axioms DualPairing.maximalMonotone_normalConeGraph_closedBall
#print axioms C0Seq.coordinateDualPairing_surjective
#print axioms Lorentz.exists_seedCounterexample
#print axioms Lorentz.seedPoint_polar_subset_carrier
#print axioms C0Seq.exists_maximalMonotone_sum_not_maximal
