import FirstOrderMethodsOptimization_Beck_2017.Chap05.Definition_5_16
import FirstOrderMethodsOptimization_Beck_2017.Chap05.Lemma_5_20
import FirstOrderMethodsOptimization_Beck_2017.Chap05.Proposition_5_13
import FirstOrderMethodsOptimization_Beck_2017.Chap05.Theorem_5_17

#print axioms is_strongly_convex_function.convex_effective_domain
#print axioms is_strongly_convex_function.ne_bot
#print axioms is_strongly_convex_function.segment_ineq
#print axioms is_strongly_convex_function.sigma_pos
#print axioms is_strongly_convex_function_iff_strongConvexOn_toReal
#print axioms strongConvexOn_toReal_of_is_strongly_convex_function
#print axioms is_strongly_convex_function_add_of_convexOn_toReal
#print axioms is_strongly_convex_function_add_of_is_convex_function
#print axioms half_squared_norm_add_indicator_is_one_strongly_convex_function
#print axioms half_squared_norm_is_one_strongly_convex_on
#print axioms effective_domain_sub_coe_eq
#print axioms is_strongly_convex_function_iff_convexOn_toReal_sub_half_sigma_norm_sq
#print axioms is_strongly_convex_function_iff_sub_half_sigma_norm_sq_is_convex
#print axioms sub_coe_neBot_of_neBot
#print axioms toReal_sub_coe_eq
