/-
Copyright (c) 2026 Zichen Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zichen Wang
-/
module

public import ReasLib.Analysis.Normed.LorentzCone.HilbertProd2

/-!
# Lorentz seed-template inequalities

These lemmas isolate the scalar and Hilbert-space estimates used by the new
seed-set construction. They keep the main construction independent of the
particular interval-coordinate realization.
-/

@[expose] public section

open scoped InnerProductSpace

universe u

namespace Lorentz

/-- The affine half-line generated by a base point and a direction is
Lipschitz whenever the direction has norm at most one. -/
theorem affine_halfLine_norm_sub_le_abs_sub {H : Type u}
    [SeminormedAddCommGroup H] [NormedSpace ℝ H] {z v : ℝ × H}
    (hv : ‖v.2‖ ≤ 1) {p q : ℝ} :
    ‖(z.2 + p • v.2) - (z.2 + q • v.2)‖ ≤ |p - q| := by
  calc
    ‖(z.2 + p • v.2) - (z.2 + q • v.2)‖ = ‖(p - q) • v.2‖ := by
      congr 1
      module
    _ = |p - q| * ‖v.2‖ := by simp [norm_smul, Real.norm_eq_abs]
    _ ≤ |p - q| := by
      exact mul_le_of_le_one_right (abs_nonneg _) hv

/-- A uniformly small perturbation of the Lorentz origin lies in the future
cone after translating by a sufficiently negative scalar parameter. -/
theorem affine_halfLine_mem_pastCone_of_small_base {H : Type u}
    [SeminormedAddCommGroup H] [NormedSpace ℝ H] {z v : ℝ × H}
    (hz : ‖z.2‖ ≤ 1 / 64) (hv : ‖v.2‖ ≤ 1 / 64) {p : ℝ}
    (hp : p ≤ 1 / 2) :
    ‖z.2 + p • v.2‖ ≤ 1 - p := by
  by_cases hpn : p ≤ 0
  · calc
      ‖z.2 + p • v.2‖ ≤ ‖z.2‖ + ‖p • v.2‖ := norm_add_le _ _
      _ ≤ 1 / 64 + |p| * (1 / 64) := by
        simp only [norm_smul, Real.norm_eq_abs]
        gcongr
      _ ≤ 1 - p := by
        rw [abs_of_nonpos hpn]
        nlinarith
  · have hpp : 0 ≤ p := le_of_not_ge hpn
    calc
      ‖z.2 + p • v.2‖ ≤ ‖z.2‖ + ‖p • v.2‖ := norm_add_le _ _
      _ ≤ 1 / 64 + p * (1 / 64) := by
        simp only [norm_smul, Real.norm_eq_abs, abs_of_nonneg hpp]
        gcongr
      _ ≤ 1 - p := by nlinarith

/-- The norm of a Hilbert product point with zero scalar component is the norm
of its Hilbert component. -/
theorem norm_hilbertProd_mk_zero {H : Type u}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] (v : H) :
    ‖HilbertProd2.mk v 0‖ = ‖v‖ := by
  have hsq : ‖HilbertProd2.mk v 0‖ ^ 2 = ‖v‖ ^ 2 := by
    simpa using (HilbertProd2.norm_mk_sq v (0 : ℝ))
  exact (sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)).mp hsq

end Lorentz
